// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfthvbfdmlozdgdodtpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmdGh2YmZkbWxvemRnZG9kdHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0Mjk0MzIsImV4cCI6MjA1MzAwNTQzMn0.Kq00ZIdesu-JB0rZ9jTwAQmlX6XGnV8o-oELYuzffk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);